matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 BITNESS=64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 BITNESS=32
install:
- docker pull $DOCKER_IMAGE
script:
- docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD make -C /io "setbufsize${BITNESS}.so"
- ls
deploy:
  provider: releases
  api_key:
    secure: LGZI4F6G7DPLv+pPBBqwrwB3n/F0M17Ly9ttLiwFlc5thtOFTAIgeAMPLO8liX4lLxAodN5424Uj3dTn574BTjJ9xoT6+jJf6OffXz2JMpySFEeZ/LYK1Vi4OShR1v6jLhoiK/1t/mRO9OY4uL2lI6aYyF+tSrLz3fiA4nv/CHbcoGqoGtoz2Z+Bk0kDfGEEdNoaZQzIWgPkI4qOk6Wcr/oSiXsgpDZov3vyJ5Hh5LfIh/czvXOprfqZRs+CfRKEgW0u2fLdvwEtg1Tw0YXSq2VVkBRWhkYSZvoaF546pGDqfSAz3KDD5O4/TTbXth2xX61Q/bEP72Xn9reogbpAiNw3U+3ztIqGGTWPneUTI3eCSquQLL85GMdOkgFHF5YSjLb0jsObEKK4IUkJt9MZ345o7yy318NAGo0MgGC6Kyui8fPVMWy+aYLeMLOfhlG2vtdSJI2Nm3Kl7Edy2UGI5ClLrD3NUQ0aleduCjQ9HU6h37QKxdD09Un7PeixZytl+UfcHgC7Xm5PSL9Od/5W68qcjuyuGGXrC6BsqoGuIT/3mF0fj+03j7YvVrCeCJ1bjycr/YpH6IwryOZvsu7P1GITGOLVWGttnQR9DhqMQUAEOqdE8XVtOC3luE803gGyQlbQv9LjqPkThzeOOHxaG4AK4h4qksva8wH0FqJqQX8=
  file_glob: true
  file: setbufsize*.so
  on:
    tags: true
